import { addIcons } from 'ionicons';
import {
  // Geral
  add,
  remove,
  close,
  closeCircle,
  search,
  searchOutline,
  arrowBack,
  chevronForward,
  chevronForwardOutline,
  chevronBack,
  chevronDownOutline,
  // Upload
  cloudUploadOutline,
  // Status
  timeOutline,
  alarmOutline,
  checkmark,
  checkmarkCircle,
  checkmarkCircleOutline,
  informationCircle,
  informationCircleOutline,
  // Cart/Bag
  cart,
  cartOutline,
  bagOutline,
  bagHandleOutline,
  bagCheckOutline,
  // Delivery
  bicycleOutline,
  storefrontOutline,
  locationOutline,
  homeOutline,
  businessOutline,
  mapOutline,
  navigateOutline,
  flagOutline,
  // Payment
  cardOutline,
  cashOutline,
  walletOutline,
  logoUsd,
  pricetagOutline,
  lockClosed,
  lockClosedOutline,
  // Chat
  logoWhatsapp,
  chatbubbleEllipses,
  chatbubbleEllipsesOutline,
  helpCircleOutline,
  callOutline,
  // User
  personOutline,
  personCircleOutline,
  mailOutline,
  // Trash
  trashOutline,
  // Password visibility
  eyeOutline,
  eyeOffOutline,
  // Pencil
  createOutline,
  // Phone
  phonePortraitOutline,
  // Benefits
  restaurantOutline,
  barChartOutline,
  // Security
  shieldCheckmarkOutline,
  star,
  starOutline,
  arrowForward,
  logIn,
  personAdd,
  qrCodeOutline,
  // Navigation
  receiptOutline,
  optionsOutline,
} from 'ionicons/icons';

export function registerIcons(): void {
  addIcons({
    add,
    remove,
    close,
    'close-circle': closeCircle,
    search,
    'search-outline': searchOutline,
    'arrow-back': arrowBack,
    'chevron-forward': chevronForward,
    'chevron-forward-outline': chevronForwardOutline,
    'chevron-back': chevronBack,
    'chevron-down-outline': chevronDownOutline,
    'cloud-upload-outline': cloudUploadOutline,
    'time-outline': timeOutline,
    'alarm-outline': alarmOutline,
    checkmark,
    'checkmark-circle': checkmarkCircle,
    'checkmark-circle-outline': checkmarkCircleOutline,
    'information-circle': informationCircle,
    'information-circle-outline': informationCircleOutline,
    cart,
    'cart-outline': cartOutline,
    'bag-outline': bagOutline,
    'bag-handle-outline': bagHandleOutline,
    'bag-check-outline': bagCheckOutline,
    'bicycle-outline': bicycleOutline,
    'storefront-outline': storefrontOutline,
    'location-outline': locationOutline,
    'home-outline': homeOutline,
    'business-outline': businessOutline,
    'map-outline': mapOutline,
    'navigate-outline': navigateOutline,
    'flag-outline': flagOutline,
    'card-outline': cardOutline,
    'cash-outline': cashOutline,
    'wallet-outline': walletOutline,
    'logo-usd': logoUsd,
    'pricetag-outline': pricetagOutline,
    'lock-closed': lockClosed,
    'lock-closed-outline': lockClosedOutline,
    'logo-whatsapp': logoWhatsapp,
    'chatbubble-ellipses': chatbubbleEllipses,
    'chatbubble-ellipses-outline': chatbubbleEllipsesOutline,
    'help-circle-outline': helpCircleOutline,
    'call-outline': callOutline,
    'person-outline': personOutline,
    'person-circle-outline': personCircleOutline,
    'mail-outline': mailOutline,
    'trash-outline': trashOutline,
    'eye-outline': eyeOutline,
    'eye-off-outline': eyeOffOutline,
    'restaurant-outline': restaurantOutline,
    'bar-chart-outline': barChartOutline,
    'shield-checkmark-outline': shieldCheckmarkOutline,
    'star-outline': starOutline,
    star,
    'receipt-outline': receiptOutline,
    'options-outline': optionsOutline,
    'arrow-forward': arrowForward,
    'log-in': logIn,
    'person-add': personAdd,
    'qr-code-outline': qrCodeOutline,
    'pencil-outline': createOutline,
    'phone-portrait-outline': phonePortraitOutline,
  });
}
